{
  "NServiceBus.DestinationSites": "Slave",
  "NServiceBus.MessageId": "e755e8fa-a56f-459f-b047-a8d301293b61",
  "NServiceBus.MessageIntent": "Send",
  "NServiceBus.ReplyToAddress": "Gateway.Slave-gateway",
  "NServiceBus.CorrelationId": "e755e8fa-a56f-459f-b047-a8d301293b61",
  "NServiceBus.OriginatingMachine": "EUES02TALP12620",
  "NServiceBus.OriginatingEndpoint": "Gateway.Master",
  "$.diagnostics.originating.hostid": "6d82e1d99ef7a18e02d8e9d3612eaf98",
  "NServiceBus.ContentType": "text\/xml",
  "NServiceBus.EnclosedMessageTypes": "Shared.Messages.InvoiceCreatedMessage, Shared.Messages, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
  "NServiceBus.ConversationId": "fa1a6a2e-735a-4370-80b8-a8d301293c7f",
  "NServiceBus.Version": "6.4.3",
  "NServiceBus.TimeSent": "2018-05-01 18:02:12:261871 Z",
  "NServiceBus.OriginatingSite": "http,http:\/\/localhost:25599\/Master\/",
  "NServiceBus.ExceptionInfo.ExceptionType": "System.InvalidOperationException",
  "NServiceBus.Retries.Timestamp": "2018-05-01 18:03:21:415191 Z",
  "NServiceBus.ExceptionInfo.HelpLink": null,
  "NServiceBus.ExceptionInfo.Message": "No handlers could be found for message type: Shared.Messages.InvoiceCreatedMessage",
  "NServiceBus.ExceptionInfo.Source": "NServiceBus.Core",
  "NServiceBus.ExceptionInfo.StackTrace": "System.InvalidOperationException: No handlers could be found for message type: Shared.Messages.InvoiceCreatedMessage\r\n   en NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext() en C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\LoadHandlersConnector.cs:línea 31\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext() en C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\DeserializeLogicalMessagesConnector.cs:línea 33\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext() en C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Performance\\Statistics\\ReceivePerformanceDiagnosticsBehavior.cs:línea 40\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() en C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Performance\\Statistics\\ProcessingStatisticsBehavior.cs:línea 27\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() en C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\TransportReceiveToPhysicalMessageProcessingConnector.cs:línea 37\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() en C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\MainPipelineExecutor.cs:línea 32\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   en NServiceBus.LearningTransportMessagePump.<ProcessFile>d__9.MoveNext() en C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Transports\\Learning\\LearningTransportMessagePump.cs:línea 277",
  "NServiceBus.TimeOfFailure": "2018-05-01 18:03:53:011572 Z",
  "NServiceBus.FailedQ": "Gateway.Slave",
  "NServiceBus.ProcessingMachine": "EUES02TALP12620",
  "NServiceBus.ProcessingEndpoint": "Gateway.Slave",
  "$.diagnostics.hostid": "ca383d7738b37d88daf3d6b2d7b241b6",
  "$.diagnostics.hostdisplayname": "EUES02TALP12620"
}